#!/usr/bin/env bash

set -eu

brew cask install google-chrome
brew cask install flycut
brew cask install shiftit

brew install node

\curl https://raw.githubusercontent.com/cppforlife/checkman/master/bin/install | bash -s
ln -s ~/workspace/setup_scripts/Checkfile ~/Checkman/setup_scripts
