#!/usr/bin/env bash

set -eu

if [ ! -f /usr/local/bin/brew ]; then
    yes | /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
else
    echo "Homebrew already installed. Skipping installation..."
fi
